language: scala
branches:
  only:
    - staging
    - trying
jdk:
  - oraclejdk9
  - oraclejdk11
sudo: false
scala:
  - 2.12.8
services:
  - docker
env:
  matrix:
    - DOCKERIMAGE=couchdb:2.2.0
    - DOCKERIMAGE=couchdb:2.3.0
    - DOCKERIMAGE=couchdb:2.3.1
  global:
    secure: ALtSdAp4wFe55/RY2+XYL8zkpwmxlIUpklbfIVzfvB+8rMMOyRxDnVbQX8DAZEqgTvQpddghOJLbqJTXwfF1MuuSVMsRpa8/iCgl6dB4fCv4YlHaLK0mb96ca0vFV0dUnp+gy9u3tNkuVAWzqlDkPf2lMreYkKlNqiqGELsFOp4=
before_install:
  - docker run -d -p 5984:5984 $DOCKERIMAGE
script:
  - sbt test
cache:
  directories:
    - $HOME/.ivy2/cache
