language: scala
jdk:
  - oraclejdk8
  - oraclejdk11
scala:
  - 2.12.8
script:
  - cd server
  - rm replicate/src/test/scala/replicate/ReplicateSpec.scala
  - sbt clean test
cache:
  directories:
    - $HOME/.ivy2/cache
