language: scala
jdk:
  - oraclejdk8
  - oraclejdk11
sudo: false
scala:
  - 2.12.8
services:
  - docker
before_install:
  - docker run -d -p 5984:5984 apache/couchdb:2.3.0
script:
  - cd server && sbt clean test
cache:
  directories:
    - $HOME/.ivy2/cache
