#! /bin/sh

cd `dirname $0`

usage() {
  cat <<"EOF"
    usage: server-pushapps local|server [user passwd [dbname]]
    user and passwd default to no authentication
    dbname defaults to steenwerck100km in local, and to the currently used database on server
EOF
}
if [ "$1" = local ]; then
  host=localhost:5984
elif [ "$1" = server ]; then
  host=steenwerck.rfc1149.net
else
  usage
  exit 1
fi
if [ -z "$2" ]; then
  auth=""
else
  auth="$2:$3@"
fi
if [ -z "$4" ]; then
  if [ "$1" = server ]; then
    dbname=`curl -s http://$auth$host/steenwerck-config/configuration |
      sed -e 's/^.*dbname":"//' -e 's/".*//'`
  else
    dbname=steenwerck100km
  fi
else
  dbname="$4"
fi

echo Pushing into $dbname at $host
full_name=http://$auth$host/$dbname
couchapp pushapps . $full_name
couchapp pushdocs _docs $full_name
