#!/bin/bash

ADMIN_USER=admin
ADMIN_PASSWD=admin
DB=localhost:5984/steenwerck100km
DOC_NAME=infos


####### DON'T CHANGE ANYTHING BELOW THAT LINE #######


DIR=$(cd $(dirname $0)/..; echo $PWD;)
source $DIR/initialize_db/update_document.bash

DOC_URL="http://${ADMIN_USER}:${ADMIN_PASSWD}@${DB}/${DOC_NAME}"


steenwerck_infos=$(cat steenwerck_infos.json)

update_document $DOC_URL "$steenwerck_infos"

# Finally, do couchapp push
couchapp push
