name: Replicate
on: [push]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["8", "11"]
    steps:
      - name: Get Ivy2 cache
        uses: actions/cache@v2
        with:
          path: ~/.ivy2
          key: ivy2-files
      - name: Checkout
        uses: actions/checkout@v2
      - name: remove Replicate test
        run: rm server/replicate/src/test/scala/replicate/ReplicateSpec.scala
      - name: Java8 SBT tests and artifacts
        if: matrix.java == '8'
        uses: lokkju/github-action-sbt@8-1.3.0-2.13.0
        with:
          commands: test
          sbt_project_directory: server
      - name: Java11 SBT tests and artifacts
        if: matrix.java == '11'
        uses: lokkju/github-action-sbt@11-1.3.0-2.13.0
        with:
          commands: test
          sbt_project_directory: server
  docker:
    needs: test
    name: docker
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: 100km/stk:latest
